18F/open-data-maker

lib/data_magic.rb, spec/spec_helper.rb, spec/tasks/indexing_spec.rb, tasks/import.rake
DataMagic class will get loaded when rake task runs
then again when server starts (or restarts)
only want to index on the rake task
fixes a bug when api didn't work at all when configuratation was required
=> import configuration when needed

INSTALL.md, sample-data/data.yaml
I hope you don't mind, but I wanted to put the data loading instructions within the INSTALL.md because it took my addled brain a little while to realize that was the next step. Also, I fixed a typo for the word `latitude`. Thank you.
=> Tweaks to installation

app/app.rb, spec/features/api_spec.rb, spec/features/web_spec.rb, spec/lib/data_magic_spec.rb
partial fix for issue #8
also API and web page integration tests
=> return json content-type

spec/fixtures/import_all/data.yaml, spec/lib/data_magic_spec.rb
same spelling error as sample-data -- thx @harrisj
=> fix spelling error

Gemfile, Gemfile.lock, app/app.rb
ended up feeling that obscuring the CORS implementation in a gem made it harder to read the code
=> remove unused gem

INSTALL.md
I'm not sure if this is the best place for it, but I added some instructions for loading custom data to the INSTALL doc. Feel free to move these to README if that's more appropriate. Or maybe these go into the wiki?
=> Add custom data instructions

app/app.rb, lib/data_magic.rb
to enable set environment variable DATA_AUTH:
export DATA_AUTH='admin,secret'
=> optional HTTP basic authentication based on env

lib/data_magic.rb
error handling should be nicer someday
=> shouldn’t crash if API endpoint not found

Gemfile, Gemfile.lock, app/app.rb, lib/data_magic.rb, spec/lib/data_magic_spec.rb
when multiple search terms are given, results should match all given terms
example: http://localhost:3000/cities?name=Chicago&state=IL
returns cities where name is Chicago AND state is IL
=> support multiple search terms

lib/data_magic.rb, spec/fixtures/import_all/more.csv, spec/lib/data_magic_spec.rb
partial fix for: https://github.com/18F/open-data-maker/issues/27
=> only index files referenced in data.yaml

Gemfile, Gemfile.lock, app/app.rb, lib/data_magic.rb, spec/features/api_spec.rb, spec/fixtures/data.rb, spec/lib/data_magic_spec.rb
fixes #13
query args page=2&per_page=30
page is a zero-based count
=> support pagination

INSTALL.md, script/bootstrap
update PR #35 and rebase on master
incorporate feedback from @monfresh
includes PR #20 integrating discussion & feedback
=> automation script, improve install instructions

app/app.rb, lib/data_magic/config.rb, spec/lib/data_magic_spec.rb
This PR creates a /data.json endpoint that returns a JSON representation of data.yaml
=> Add /data.json representation of data.yaml

lib/data_magic.rb, spec/lib/data_magic/import_with_dictionary_spec.rb
=> Only search documents.

CONTRIBUTING.md, INSTALL.md, README.md
clarifications to INSTALL, README (rake import not required)
CONTRIBUTING: +slack channel! default dev branch
plus new guidance on branch naming dev-your-feature
=> documentation improvements

lib/data_magic.rb, lib/data_magic/index.rb, sample-data/data.yaml, spec/lib/data_magic/config_spec.rb, spec/lib/data_magic/search_spec.rb
sample-data is now specified (via data.yaml) to be unique on city name
=> make it so sample-data can be re-imported without deleting index

app/app.rb, lib/data_magic.rb, script/s3pull, script/s3push, spec/features/api_spec.rb, spec/lib/data_magic/search_spec.rb
sort=field_name:asc
sort=field_name:desc
fixes issues #95
=> sort by any field

lib/data_magic/query_builder.rb, spec/lib/data_magic/query_builder_spec.rb
As suggested by @shawnbot in #52.
=> Support "__not" as synonym for "__ne"

lib/data_magic/index.rb, lib/data_magic/query_builder.rb, spec/lib/data_magic/import_with_dictionary_spec.rb
this should really have a test!
=> default distance units

Gemfile.lock
=> update rack & activesupport

lib/data_magic/query_builder.rb, spec/lib/data_magic/import_with_nested_files_spec.rb
=> fix for sorting nested fields

.gitignore, .rubocop.yml
@ultrasaurus, can you OK these?
=> Dotfile updates (.gitignore, .rubocop.yml)

lib/data_magic.rb, lib/data_magic/index.rb, spec/lib/data_magic/import_with_dictionary_spec.rb
this saves tons of debugging time
=> catch yaml type errors

app/controllers.rb
uses data.yaml dictionary to determine csv column order
=> csv output should have columns in data.yaml order

lib/data_magic/index.rb
when parent id is missing for nested row, collect the ids and log at end of file
=> more concise logging of skipped rows

.travis.yml
... which are meant to be much faster.
=> Test Travis docker builds

lib/data_magic.rb, lib/data_magic/index.rb, lib/data_magic/query_builder.rb, spec/fixtures/school_names/data.yaml, spec/fixtures/school_names/school_names.csv, spec/lib/data_magic/search_name_spec.rb
I believe this addresses https://github.com/18F/open-data-maker/issues/179
=> better search

spec/features/api_spec.rb, spec/lib/data_magic/search_spec.rb
... of the kind fixed here: https://github.com/18F/open-data-maker/commit/b909d4e3ac576423c7278631bac0ddf48bb414cc
=> Extra pagination tests to spot nasty bugs

lib/data_magic/config.rb, lib/data_magic/document_builder.rb, lib/data_magic/query_builder.rb, spec/features/api_spec.rb, spec/lib/data_magic/search_name_spec.rb
this isn't elegant, but it I believe it works
=> autocomplete type alpha sort

lib/data_magic.rb, lib/data_magic/query_builder.rb, spec/lib/data_magic/query_builder_spec.rb
Fixes #191 and https://github.com/18F/college-choice/issues/1155
=> Only allow up to MAX_PAGE_SIZE per page

Gemfile, Gemfile.lock, lib/data_magic.rb, lib/data_magic/query_builder.rb, spec/lib/data_magic/query_builder_spec.rb, spec/lib/data_magic/search_name_spec.rb
Also, use the ES result `took` key to get the query time in ms.
=> Use `_source: false` to limit JSON coming back from ES

manifest.yml
Ensures the elk log drain service is bound when deploying.
=> adds binding for the elk logger

API.md
Update to real production urls
=> update to real urls

API.md
=> more API docs

API.md, manifest.yml
This is a temporary necessity until we push college scorecard to production again with an updated link to docs on dev
=> Updates api-docs branch to have latest docs from dev

INSTALL.md
Updated INSTALL.md to include homebrew elastic search command
=> Add brew install elasticsearch to INSTALL.md

lib/data_magic/document_builder.rb, spec/lib/data_magic/document_builder_spec.rb
this supports having an OR expression resulting in a boolean
where the source might be integer or float columns
and the new column would be true or false
needed for https://github.com/18F/college-choice/issues/951
=> Bool expressions

lib/data_magic/config.rb
S3 library only fetches 1000 keys, 
so file_list method would fail when directory had lots of files
easy fix removes file_list method entirely, just attempts to read
file and deals with failure
resolves #250
=> don’t rely on file listing to check file exists

lib/data_magic/config.rb, spec/lib/data_magic/config_spec.rb, spec/lib/data_magic/import_without_data_yaml_spec.rb, spec/lib/data_magic/search_spec.rb
In some cases I didn't add extra logging since I'm raising a very specific error
when reviewing pls think about if there are additional spots where you think logging would be helpful 
resolves #254 and #255
=> better handling of failure to load config data file

lib/data_magic.rb, lib/data_magic/config.rb, spec/lib/data_magic/config_spec.rb, spec/lib/data_magic/import_without_data_yaml_spec.rb
not sure this is the best way to test, but it seems to work
resolves issue #268
=> handle s3 errors better

Gemfile.lock
... so as to use the new Error Analytics features.
=> Update New Relic gem

API.md
... as required by https://github.com/18F/college-choice/issues/1378
=> Document location field issue #227

.ruby-gemset
* Separates the gems needed for this application, from other
ones in this Ruby version
* Maybe should be named for college score card, not sure how
these apps fit together
=> Adds a .ruby-gemset

manifest-dev.yml, manifest-ex.yml, manifest-production.yml, manifest-staging.yml
this should make the ci tests pass
=> elk-logger no longer used in our cf environments

manifest-dev.yml, manifest-ex.yml
we only need 3 instances on production
=> fixup manifests

INSTALL.md, README.md
we don’t index at app start anymore
=> docs for indexing
