18F/open-data-maker

app/app.rb, lib/data_magic.rb, spec/fixtures/import_all/data.yaml, spec/lib/data_magic_spec.rb
this makes it so API requests can work without code change, and also I think I've fixed it so default case should work with default index name and csv columns, but test coverage might be weak on that use case
=> support getting index from api endpoint name

Gemfile, Gemfile.lock, Procfile, config/unicorn.rb, lib/data_magic.rb, manifest.yml, tasks/cloud_foundry.rake
start app with unicorn
using data.yaml version field in the cf:index rake task
probably should be used in index:all, but going to test this with additional data sets before refactoring
=> cloudfoundry deploy: index when needed, on push

README.md
Exporting bash variables only requires one `export` :)
=> Removing double 'export' typo in README

lib/data_magic.rb, lib/data_magic/config.rb, lib/data_magic/index.rb, sample-data/data.yaml, spec/features/api_spec.rb, spec/fixtures/geo/data.yaml, spec/fixtures/import_with_dictionary/data.yaml, spec/lib/data_magic/config_spec.rb, spec/lib/data_magic/search_spec.rb
partial implementation of issue #8
global_mapping renamed to dictionary
field name is now the key 
source: specifies the column name
types can be specified, but aren't hooked up
=> new data.yaml dictionary format

app/app.rb, spec/features/api_spec.rb
Motivation: IMO, APIs should be self-documenting where possible, and users shouldn't have to hit a 404 to find a list of valid endpoints.
* Add an endpoint that lists available data endpoints with URLs:
```
{
"endpoints": [
"name": "cities",
"url": "/cities"
],
...
}
```
* Throw a real 404 on missing pages (previously, we were returning a 200 status code with a 404 error message
* Update tests
I don't know which other routes you all were thinking of adding going forward, so if the proposed `/endpoints` route conflicts with anything, I'm happy to revise. I was thinking of having `/` return a list of endpoints instead of HTML, but figured you might have plans for that route.
=> List endpoints

NOTES.md
we no longer use DATA_VERSION
also, added details about how to specify S3 in DATA_PATH
fixes: https://github.com/18F/open-data-maker/issues/50
=> update NOTES to match current state of the code

app/app.rb, lib/data_magic.rb, spec/features/api_spec.rb, spec/fixtures/data.rb, spec/lib/data_magic/search_spec.rb
library #search now supports 'fields' option
application API expects comma-separated list, like: fields=name,another
fixes: https://github.com/18F/open-data-maker/issues/76
=> Allow result to contain only specific fields (not the whole document)

app/views/home.liquid
1. Cleans up HTML and Liquid whitespace
2. Changes the "API endpoints" heading to an `<h2>`
2. Wraps the endpoints in links so you can click on them to see data!
=> Home page template tweaks

lib/data_magic.rb, lib/data_magic/config.rb, lib/data_magic/index.rb, spec/lib/nested_hash_spec.rb
after testing with more types, and with more nested fields, I realized that whenver there is a new mapping, we need to delete the index and re-index all the data.  Technically we could add a column without re-indexing, but this will work for starters.
Also made logging less verbose, truncating so lines for really big data.yaml
=> new mapping requires new index

Gemfile, Gemfile.lock, config/env.rb
Note: Requires `NEW_RELIC_LICENSE_KEY` and `NEW_RELIC_APP_NAME` env vars set in each environment. The license key is the same each time, but app name will be different (e.g. `CC-API (Dev)`, `CC-API (Staging)` etc.)
=> Initial New Relic setup

lib/data_magic.rb, lib/data_magic/config.rb, lib/data_magic/index.rb, spec/features/api_spec.rb, spec/fixtures/nested2/data.yaml, spec/fixtures/nested2/school2013.csv, spec/fixtures/nested_files/data.yaml, spec/lib/data_magic/config_field_types_spec.rb, spec/lib/data_magic/import_with_dictionary_spec.rb, spec/lib/data_magic/import_with_nested_files_spec.rb
for example, the following queries now work:
http://localhost:3000/school?school.degrees_awarded.predominant=3&fields=id,school.name,school.degrees_awarded.predominant
http://localhost:3000/school?school.zip=99645&fields=school.zip,id,school.name
note: there is a pending test, right now error reporting for incorrect type from data.yaml is broken
=> specify complete mapping to supported full path nested queries

lib/data_magic.rb, lib/data_magic/query_builder.rb, sample-data/data.yaml, spec/features/api_spec.rb, spec/fixtures/nested2/data.yaml, spec/fixtures/nested_files/data.yaml, spec/lib/data_magic/config_spec.rb, spec/lib/data_magic_spec.rb
integrates change by @ridiculus that allows us to have a name that will support an exact match
data.yaml now can have a 'literal' type for this behavior
```
dictionary:
name:
source: NAME
type: literal
```
=> create custom type ‘literal’ for not_analyzed text

lib/data_magic/index.rb
don’t want to mask other exception when there’s a UTF-8 error
now we *should* raise the correct (unexpected) exception
=> better error catching / raising

app/views/home.liquid, sample-data/data.yaml
Currently links will only work if hosted at the root of a domain. This PR will make them relative, so that if the app is mounted at a subpath (in our case, proxied via api.data.gov) the links will still work.
=> make API links relative

lib/data_magic.rb, lib/data_magic/config.rb, lib/data_magic/index.rb, lib/data_magic/query_builder.rb, spec/fixtures/types/data.yaml, spec/fixtures/types/places.csv, spec/lib/data_magic/config_spec.rb, spec/lib/data_magic/import_without_data_yaml_spec.rb, spec/lib/data_magic/name_type_spec.rb
technically we index as ‘not analyzed’
then query with wildcard match at end of each word
Searching for "New" should find "New York" and "New Orleans"
Searching for "New York" should find "New York" 
Searching for "Boston Univ" should find "Boston University"
=> new ‘name’ type allows more intuitive searching for names

lib/data_magic.rb, lib/data_magic/config.rb, lib/data_magic/index.rb, lib/data_magic/query_builder.rb, spec/lib/data_magic/name_type_spec.rb, spec/lib/data_magic/query_builder_spec.rb
for every field of type name, this commit indexes two fields
the original text and another that is lowercase and prefixed by _
for example, if we have a field city: New York
then we make another field _city: new york
we search on "_city" but only include "city" in results
=> Case insensitve search

lib/data_magic/config.rb, lib/data_magic/document_builder.rb, lib/data_magic/index.rb, lib/expression.rb, spec/lib/data_magic/calculated_columns_spec.rb, spec/lib/data_magic/config_spec.rb, spec/lib/data_magic/document_builder_spec.rb, spec/lib/expression_spec.rb
this addresses a bug in PR #165 where case insentive search would fail
if it was for a field specified as part of an "only" configuration
for example, in data.yaml
```
files:
- name: school-data.csv
only: [id, name, city, state]
```
would select only the fields id, name, city, and state from that particular file.  
Other files may include other fields in the dictionary.  The bug was that it 
would include name, but omit _name (which is never visible to the user, 
but required for case insensitive indexing.
note: with this option, if dot syntax is used, only top level fields may be specified
=> fixed indexing of "name" type when files have "only" option

README.md, app/controllers.rb, lib/data_magic.rb, lib/data_magic/config.rb, lib/data_magic/error_checker.rb, lib/data_magic/index.rb, lib/data_magic/query_builder.rb, sample-data/data.yaml, spec/features/api_spec.rb, spec/fixtures/nested2/data.yaml, spec/fixtures/nested_files/data.yaml, spec/lib/data_magic/config_spec.rb, spec/lib/data_magic/error_checker_spec.rb, spec/lib/data_magic/import_with_nested_files_spec.rb, spec/lib/data_magic/query_builder_spec.rb, spec/lib/data_magic/search_spec.rb
Calling this "part 1" because there are still errors not yet handled (in which case, it'll just blow up with a 500 as usual) but @ultrasaurus agreed that Some Error Handling is better than none.
The ErrorChecker module scans the arguments sent to search and looks for badness. It compiles an array of error hashes, each of which includes an `error` code, a human readable `message`, the problematic `input`, and in certain cases some other entries with additional data. (See `spec/lib/data_magic/error_checker_spec.rb` for examples)
If the ErrorChecker finds errors, the API will return HTTP 400 along with a JSON object with the errors array under `errors`.
Errors currently handled:
* Parameter not found
* Field not found (in a `fields` parameter)
* Operator not found (if not `range`, `ne` or …
=> API error handling, part 1

lib/data_magic/error_checker.rb, spec/lib/data_magic/error_checker_spec.rb
@shawnbot noticed that the totally valid range `2..3` was raising an error, so this fixes that.
=> Fix for range format bug

lib/data_magic/document_builder.rb, spec/lib/data_magic/document_builder_spec.rb
In ruby, 0 evaluates to true, but that’s not expected out of context
handles integers and floats
=> in dictionary calculate expresssion, 0 -> false

app/controllers.rb, lib/data_magic.rb, spec/features/api_spec.rb, spec/fixtures/sample-data/data.yaml, spec/lib/data_magic/error_checker_spec.rb
Implements #176. Non-prefixed option parameters are deprecated but still supported; see `SUPPORT_DEPRECATED_OPTION_SYNTAX` in `controllers.rb`. Once this is turned off, the specs added to the end of `api_spec.rb` should be switched from pending to non-pending and vice versa.
@ultrasaurus @siruguri - does this code make sense?
=> option parameters should now be underscore-prefixed

lib/data_magic/error_checker.rb, lib/data_magic/query_builder.rb, spec/lib/data_magic/error_checker_spec.rb, spec/lib/data_magic/query_builder_spec.rb, spec/lib/data_magic/search_spec.rb
Now a comma-separated list of integers can be supplied to any integer field parameter:
```
/v1/schools?id=1,2,3
```
... should return a list of the three records with those IDs.
Implements https://github.com/18F/college-choice/issues/948.
=> Match from a list of integers

app/controllers.rb
As discussed in https://github.com/18F/college-choice/issues/990 - this adds
```
Cache-Control: public, max-age=300
Surrogate-Control: max-age=300
```
to all `v1` API headers.
Explanation:
* We've chosen an initial TTL of five minutes until we're more confident of not needing to rush data fixes.
* `max-age=300` is the same as `expires` and `s-max-age`.
* `public` because there's no private info, and an ISP cache should be free to share any results
* `Surrogate-Control` is only seen by the `api.data.gov` cache, and is the TTL value we'll increase first when we do. (At present there's no easy way for us to flush their cache.)
=> Add caching headers

app/controllers.rb, lib/data_magic.rb
The ES query is now timed and logged; also available in the JSON response if you add `_debug=1` to the URL
=> Log ES query time, and show with "debug" option

config/unicorn.rb
This is for testing a scalability bottleneck we're observing in load testing.  If I'm reading the documentation correctly at http://unicorn.bogomips.org/Unicorn/Configurator.html, there is no parallelism in request processing in Unicorn and having this set to 1 implies the server can only serve a single concurrent request at any time.
=> Increase unicorn workers from 1 to 5

manifest.yml, notes.txt
increasing the number of unicorn workers requires an increase in memory
this PR makes that persistent by specifying it in the manifest
=> increase in unicorn workers requires more memory

app/app.rb
Presently api.data.gov is unable to cache responses because it considers responses with Set-Cookie headers uncacheable (rightly so).  This app is completely stateless and has no need for session tracking, so this PR disables session support.  Further, CSRF protection is not useful if you have no cookies maintaining an authenticated session (and Padrino gripes if you attempt to disable sessions by itself), so disable that protection as well.
=> Disable sessions (therefore CSRF protection) to permit caching

manifest.yml
Sets reasonable defaults for a Puma-based configuration based on the load testing results in 18F/college-choice#597.  In this configuration we can handle roughly 2400rpm with ES being the bottleneck.
These are defaults only, take effect with every 'cf push', and can be overridden with the cf command line tool.
=> Set instances and env var defaults

INSTALL.md
Fix the sample URL query to reflect the v1 endpoints
=> Fix URL in documentation

API.md, lib/data_magic/config.rb, lib/data_magic/index.rb, manifest.yml, spec/lib/data_magic/create_index_spec.rb
Created a `DataMagic::Config.index_exists?` method to ensure that the
index only gets created once. If the index exists after the app starts
subsequent calls to  `#import_with_dictionary` and `#import_csv`
will not trigger index creation.
On the other hand, if the index is not present on app start, then
those actions will create the index.
The logs look cleaner now as they only report on index creation once. 
I'm not sure if the test coverage is sufficient and covers all possible entry points,
so let me know if more tests are needed. 
Working on issue #135
=> Index creation

CONTRIBUTING.md
An update to the `CONTRIBUTING.md` guide to fix the incorrect reference to the `master` branch for pull requests.
=> Fix git branch reference in Contributing.md

INSTALL.md, script/bootstrap
Before, the bootstrap script eagerly installed the most recent version
of elasticsearch. While this is normally a "good thing", open data maker
uses conventions that are no longer supported in elasticsearch 2.0.0
Now, ensure elasticsearch 1.7.3 is installed.  Also, update README to
indicate the current situation.
=> Fix bootstrap script.

lib/data_magic/error_checker.rb, lib/zipcode/zipcode.rb, spec/lib/data_magic/error_checker_spec.rb, spec/lib/zipcode_spec.rb
Putting this in ErrorChecker although we may want to refactor some other way? Zipcodes aren't in every dataset.
=> Dev 213 invalid zipcode should report error

.rubocop.yml
=> Remove obsolete RunRailsCops rubocop directive

lib/data_magic.rb, lib/data_magic/error_checker.rb, spec/lib/data_magic/error_checker_spec.rb
Note: the following URLs used to error with stack traces in NewRelic, now have proper json error reporting
- http://localhost:3000/v1/schools?distance=4
```
{
"errors": [
{
"error": "distance_error",
"message": "Distance requires zipcode (none given)."
}
]
}
```
- http://localhost:3000/v1/schools?zip=000
```
{
"errors": [
{
"error": "zipcode_error",
"parameter": "zip",
"input": "000",
"message": "The provided zipcode, '000', is not valid."   
}
]
}
```
=> fix various errors we're seeing in NewRelic

Gemfile, Gemfile.lock, lib/data_magic.rb, lib/data_magic/config.rb, lib/data_magic/index.rb, lib/data_magic/index/importer.rb, lib/data_magic/index/output.rb, spec/lib/data_magic/config_spec.rb, spec/lib/data_magic/index/importer_spec.rb
re-implements #94 
supersedes #295 and #296 (rebased on dev)
This PR cuts indexing time significantly when run on a machine with multiple processors, at the expense of more memory usage. To mitigate the additional memory use that comes with parallel (forked) processes, CSV files are read via IO stream, a row at a time, rather than being slurped entirely into memory and parsed as a String.
For reference, the current import consumes about 250MB for the single process.
Example stats and usage:
```
NPROCS=1 rake import
NPROCS=4 CHUNK_SIZE=50 rake import
NPROCS=5 CHUNK_SIZE=100 rake import
```
An important caveat with reading CSV as stream: the :force_utf8 feature does not work as currently implemented. My recommendation is to require all CSV files be in UTF-8 format prior to import, possibly …
=> Elasticsearch bulk index
